---
name: Build, Push and Deploy NodeJS Image w/ Google Cloud Platform
on:
  push:
    branches: [ci]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo NEO4J_USER=${{ secrets.NEO4J_USER }} >> .env
          echo NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }} >> .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo NEO4J_PASSWORD_TEST=${{ secrets.NEO4J_PASSWORD_TEST }} >> .env
          echo NEO4J_URI_TEST=${{ secrets.NEO4J_URI_TEST }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo NEO4J_URI=${{ secrets.NEO4J_URI }} >> .env
      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run dev-test

  build-push-gcr:
    needs: test
    name: Build and Push Docker Image to GCP Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: xandria
      PROJECT_ID: xandria-web
      REPO_ID: xandria

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Push Image to Artifact Registry
        run: |-
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest .
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest

  deploy-run:
    needs: build-push-gcr
    name: Deploy Image with GCP Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Google Cloud Run
        id: deploy-run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: xandria
          image: europe-west3-docker.pkg.dev/xandria-web/xandria/xandria:latest
          region: europe-west3
          flags: --allow-unauthenticated
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Test deployment
        run: curl "${{ steps.deploy-run.outputs.url }}"
